### ISSUE TITLE
Consejo visual

### ISSUE THREAD

**Issue by NicolasLeon05** [MacGiv/Desarrollo1_Pixeloids#6]
Cuando el player sale de la pantalla y reaparece al lado contrario se siente muy de golpe, Haciendo estos pequeños cambios se siente mucho mas fluido y natural
![Screenshot_2](https://github.com/user-attachments/assets/63510acc-cd03-4ef8-97a3-dbdb49a5cffe)

**Comment by MacGiv** [comment]
Agregado, gracias!
